name: Terraform Deploy

on:
  push:
    branches:
      - main # Triển khai khi có push vào nhánh main
  pull_request:
    branches:
      - main

env:
  WORKING_DIRECTORY: "./Assignment01/Terraform"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6 # Chọn phiên bản Terraform

      - name: Run Terraform Init
        run: terraform init

      - name: Run Terraform Validate
        run: terraform validate

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ env.WORKING_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6 # Chọn phiên bản Terraform

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan
        id: plan
        run: terraform plan
        env:
          TF_VAR_ami_id: ${{ vars.AWS_AMI_ID }}
          TF_VAR_device_ip: ${{ vars.DEVICE_IP }}
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          TF_VAR_ami_id: ${{ vars.AWS_AMI_ID }}
          TF_VAR_device_ip: ${{ vars.DEVICE_IP }}
        working-directory: ${{ env.WORKING_DIR }}
